### PR TITLE
added method to remove emojis from string + test

### PR DESCRIPTION
**Pull request by gidim**

### CODE REVIEW

**Comment by vdurmont** [comment]
It seems great!

I was thinking of merging your PR and adding a few methods for more flexibility:

* `EmojiParser.removeAllEmojis(String)` is the one you just commited, it would remove all the emojis
* `EmojiParser.removeEmojis(String, Iterable<Emoji>)` would only remove the emojis in the `Iterable`
* `EmojiParser.removeEmojisExcept(String, Iterable<Emoji>)` would only remove all the emojis, except the ones in the `Iterable`

What do you think?

**Comment by gidim** [comment]
Ya sounds great! I'm cleaning up all the emojis so I could do language identification but I'm sure others will be interesting in only removing a subset.

**Comment by vdurmont** [comment]
Perfect I'll work on it!

**Comment by gidim** [comment]
Cool!

**Comment by vdurmont** [comment]
You can upgrade to the version 2.2.0, it contains the new methods!

**Pull request merged**
