### PR TITLE
fix EmojiParser extractEmojis

### PR DESCRIPTION
**Pull request by sullis**
- respect fitzpatrick modifiers

### CODE REVIEW

**Comment by sullis** [comment]
@vdurmont

**Comment by vdurmont** [comment]
Thank you!

**Comment by sullis** [comment]
@vdurmont  can you release a new version of the library?

**Comment by vdurmont** [comment]
Yes, I will do that today! I'd like to try to take a look a #137 if I can before that but if I don't have time, I'll release today anyway.

**Comment by vdurmont** [comment]
@sullis I just checked, it reached maven central! v5.1.1

**Comment by sullis** [comment]
@vdurmont  Awesome!  I just upgraded to v5.1.1

https://github.com/sullis/twilio-sms-example-java/commit/927692652736467390343baa4754809d5191cf05

I pushed my code to production.  It works! 💯

**Pull request merged**
