### PR TITLE
removed Variance Selector from U+263A emoji

### PR DESCRIPTION
**Pull request by roberterdin**
This should fix the bug in #38

### CODE REVIEW

**Comment by vdurmont** [comment]
Thanks for the help! It looks good to me. I'll let @Lolologist take a look too since he's currently working on supporting the Variance Selectors in *emoji-java*, he will probably have an opinion!

As soon as this is merged, I'll release a new version on Maven Central.

**Comment by roberterdin** [comment]
there were more variance selectors. Should be all now

**Comment by Lolologist** [comment]
I hope to more properly cover those in the nearish future, but can't get to
it for something on the order of a couple of weeks. I definitely would like
to make sure this is properly handled!

-Daniel

**Comment by vdurmont** [comment]
I just published a new version on Maven Central with this change: v3.1.3

**Pull request merged**
