### PR TITLE
add support for hex encoded html codes

### PR DESCRIPTION
**Pull request by frindly**
I love the library, but my servers are returning html emoji in hex.  This change add support for hex.

### CODE REVIEW

**Comment by vdurmont** [comment]
Hey! Thank you for the pull request!

I think that adding the support for hex encoded html codes is a very good idea.

The problem is that the modification you made breaks the API for those who already use the library (the `Emoji#getHtml()` method disappears) so it would force a bump to a 2.0.0 version according to [semver](http://semver.org/).
I think it would be better to go to `v1.1.0` and include the following methods:
* `Emoji#getHtmlHexCode()`
* `Emoji#getHtmlDecimalCode()`
* `@Deprecated Emoji#getHtml()`: returns the result from `getHtmlDecimalCode()`

Also, we could deprecate `EmojiParser#parseToHtml` and create `EmojiParser#parseToHtmlDecimal` and `EmojiParser#parseToHtmlHexadecimal`.

* What do you think about that?
* If you agree, do you want to update your pull request or do you want me to merge and make the changes?

**Comment by frindly** [comment]
Good point about breaking the API -- I like adding the new methods and
deprecating the getHtml().

In terms of parseToHtml - I'm not sure about adding separate Decimal and
Hexadecimal methods, I think it is probably not something most people will
care about and its nicer not to make people have to think about it.

What about instead adding an overload that takes an enum Hex or Decimal,
and leaving the current method and have it default to the current decimal
parsing?

Let me know what you think and I'll go ahead and update the pull request.

Thanks,

Jake

**Comment by vdurmont** [comment]
I think we have to keep a consistency between the objects.

* If we choose that the decimal notation is the default for html, then we should have:
    * `Emoji#getHtml()` returns the decimal code
    * `Emoji#getHtmlHexCode()` returns the hexadecimal code (or `getHtml(Type.HEX)` as you suggested)
    * `EmojiParser#parseToHtml()` parses using the decimal code
    * `EmojiParser#parseToHtmlHexadecimal()` parses using the hexadecimal code (or `parseToHtml(Type.HEX)` as you suggested)
* If we want to modify the API and make a real difference, then we would have:
    * `@Deprecated Emoji#getHtml()` returns the decimal code
    * `Emoji#getHtmlDecimalCode()` returns the decimal code
    * `Emoji#getHtmlHexCode()` returns the hexadecimal code
    * `@Deprecated EmojiParser#parseToHtml()` parses using the decimal code
    * `EmojiParser#parseToHtmlDecimal()` parses using the decimal code
    * `EmojiParser#parseToHtmlHexadecimal()` parses using the hexadecimal code

Both solutions seem ok (I have a preference for the second one) but I don't want to "mix them". I think it can be misleading to have a difference between `Emoji#getHtml()` and `Emoji#getHtmlDecimal()` but not between `EmojiParser#parseToHtml()` and `EmojiParser#parseToHtmlDecimal()`.

I understand your argument that consists in making things easier for the user but it's difficult to be sure that the decimal notation will be used more than the hexadecimal one (and thus should be the default).

What do you think?

**Comment by frindly** [comment]
You make good points.  My preference is would be the second option. Most
users probably don't care about hexadecimal vs decimal so I think it would
be nicer to keep the vanilla get html method.  The parser will still "just
work" either way.

If that sounds good to you I will make the changes and update the pull
request.

Jake

**Comment by vdurmont** [comment]
Yes sounds good!

**Pull request merged**
