### PR TITLE
Reorder Emoji to Unicode Master List

### PR DESCRIPTION
**Pull request by searchy2**
> Added over 400 missing emojis
> Fixed 2 wrong Fitzpatrick modifiers
> Ordered emojis in order of official emoji list
> All previous emoji aliases retained for backwards compatibility, official emoji shortcode added whereever appropriate

### CODE REVIEW

**Comment by searchy2** [comment]
Can you look at the tests and help me make sense of them? I think they might have something to do with the additional flags and maybe some aliases? Thank you!

**Comment by vdurmont** [comment]
> Ordered emojis in order of official emoji list

I'd really like to review but it is almost impossible: the whole emoji file has been changed 😢 

If I understand correctly, you used this spreadsheet? https://1drv.ms/x/s!ArQt_o2-63zph4RM_gJWdKGRKeRGYw

If you get all the tests to pass, it would be easier to merge, I'd be more confident that we're not going to break everything 😄 

Regarding the failure of `getAllTags_returns_the_tags`: you added new emojis, you have to change the expected number. This is just a test to make sure we do not add/remove emojis without noticing.

**Comment by searchy2** [comment]
@vdurmont Thanks for taking a look at my PR. There are WAY too many changes to properly review so I definitely understand :astonished: 
I was hoping you would provide more insight as to the errors I am seeing but that might be a difficult task (hey, adding 400 additional emojis is difficult!) 
Here is what I am going to do. I will base a new PR on #45 but not add any additional emojis. Instead, I will take all the emojis in the latest json, convert it to excel, sort it based on Unicode order, and then convert back to JSON. Then I will test the commit and see if it passes the tests. If not, then that will mean my process is flawed and will need to be fixed. 

How are you editing the JSON? I convert to Excel but do you have an easier method?

**Comment by freva** [comment]
@searchy2 Depends on what you need in the editor? I use Nodepad++ most of the time, it can do basic highlighting and bracket checking. Otherwise, in my main IDE, which is IntelliJ IDEA, you can collapse the elements, which I guess might be helpful sometimes...

As far as the errors go, I think you missed a lot of emojis that were here before or there must have been some sort of error when translating between Excel/JSON. When I run your changes, I get 8 errors, here's half of them:

- EmojiManagerTest.getAllTags_returns_the_tags() Complains about the number of unique tags in the database, the expected is 594 while yours returned 341. So I guess you must have either removed some emojis or changed their tags so that there are fewer of them.
- EmojiParserTest.parseToUnicode_with_the_keycap_asterisk_emoji_replaces_the_alias_by_the_emoji() Complains that there is no emoji with "keycap_asterisk" or "star_keycap" alias.
- EmojiParserTest.parseToUnicode_with_the_thumbsdown_emoji_replaces_the_alias_by_the_emoji() Complains that there is no emoji with alias "-1"

- EmojiParserTest.parseToUnicode_with_the_thumbsup_emoji_in_hex_replaces_the_alias_by_the_emoji() complains that there is no emoji with alias "+1"

**Comment by searchy2** [comment]
Ok, the latest 2 checks have both passed. That means the conversion process from JSON>>Excel>>JSON is solid. Errors are a result of MY manipulation and I am at fault. Time to fix that!

**Comment by searchy2** [comment]
Mother of **** 
The reason the tests are failing is because Excel is turning certain aliases into equations. The "+1" for thumbs up is being turned into 1 which is causing the entire build to fail. I am so stupid :frowning:

**Comment by searchy2** [comment]
Reordered emojis to order of Unicode order. Please review, thank you!

**Comment by whitecat** [comment]
What is the status on the PR?

**Comment by searchy2** [comment]
The emojis are reordered successfully and can be merged with no conflicts.

**Comment by searchy2** [comment]
@vdurmont Can we discuss why this PR is not being merged? New updates were made which makes this PR in conflict with Master. At the time of submission however, there were no conflicts. 

I still believe it is important to organize the list of emojis in the same order as the Unicode master list. It makes making additions and changes much easier.

**Comment by Tapchicoma** [comment]
I really like your idea, but @vdurmont is right - it is a really hard to review such changes.

Is it possible to split this huge json file into the smaller ones? For example, based on emoji categories?

**Comment by searchy2** [comment]
Closing due to outdated emoji list.

**Pull request closed without merging**
